#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true

bspc rule -a Chromium desktop='^2' follow=off
bspc rule -a discord desktop='^3' follow=off
bspc rule -a firefox desktop='^4'
bspc rule -a Spotify desktop='^5'
bspc rule -a Thunderbird desktop='^6'
bspc rule -a Zathura desktop='^7' state=tiled follow=on
bspc rule -a libreoffice-startcenter desktop='^9'
bspc rule -a libreoffice-writer desktop='^9'
bspc rule -a libreoffice-calc desktop='^9'
bspc rule -a libreoffice-math desktop='^9'
bspc rule -a Gimp desktop='^10' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=floating --one-shot

#start up script
~/startupscripts/./bspwmstart.sh
